### ISSUE TITLE
Is this project abandoned?

### ISSUE THREAD

**Issue by madsh93** [chakra-ui/chakra-ui-vue-next#136]
I don't see a lot of activity, but I was hoping to try Chakra with Nuxt 3. Is this project still active?

**Comment by codebender828** [comment]
Hey @madsh93 ! No, project is not abandoned. We just have limited time to contribute outside our work hours. Recently lots of events happening personally.

I hope to resume activity this month. If your project is urgent, I recommend that you use a different stack for now. I believe it will be a couple of months before we're ready to roll out everything.
