### ISSUE TITLE
Github profile link is incorrect

### ISSUE THREAD

**Issue by hugobqd** [chakra-ui/chakra-ui-vue-next#165]
Hello!
The link `next.vue.chakra-ui.com` in the github page is incorrect.
It should be https://vue.chakra-ui.com I suppose.

<img width="321" alt="Capture d’écran 2022-09-13 à 10 13 18" src="https://user-images.githubusercontent.com/35178/189848016-1df5f94b-f6f6-4f85-a559-1fed9c53086e.png">

<img width="534" alt="Capture d’écran 2022-09-13 à 10 15 13" src="https://user-images.githubusercontent.com/35178/189848479-43aec802-387b-47b8-879d-03a8bc979eeb.png">

Thanks for your work! <3 chakra

**Comment by carwack** [comment]
Hi @hugobqd,

Thanks for letting us know. 
The link you proposed (vue.chakra-ui.com) is for the v0.x version of Chakra UI Vue, which works for Vue 2.

But this repo, the Chakra UI Vue Next, is for the v1 version of Chakra UI Vue, which is compatible with Vue 3. And so we have a new URL for the upcoming documentation for the v1 of Chakra UI Vue which is currently under construction.

I will close this issue now.

Kind regards
