### ISSUE TITLE
Update `CONTRIBUTING.md`

### ISSUE THREAD

**Issue by TylerAPfledderer** [chakra-ui/chakra-ui-vue-next#168]
During the process of fixing and updating my local environment to ensure everything is working (at least in the scope of running the development playground) I noticed that the information in the `CONTRIBUTING.md` file does not quite line up in the successful steps I actually took.

And based on the configuration of the package as a Windows OS user, it might also be good to have a section for those specific users with suggestions on troubleshooting any issue to get their local environment working properly without compromising the package.

Current suggestions:
- Change the `Setup the Project` section: `Fork repo > clone locally > run yarn install (installs deps and build the packages) > run yarn playground:dev (runs the Vite playground)`
  - Currently, it suggests running `yarn build` and `yarn bootstrap` which seem to be unnecessary based on the scripts used in other steps.
- Mention `yarn playground:dev` script in `Commands` section
  - `yarn dev` currently does nothing but validate `preconstruct dev` and not actually boot up the playground
- Add `For Windows Users` section to address suggestions in ensuring the local environment in that OS operates properly
  - Ensure node version used is greater than `v16.16.0`
  - Use the `win-node-env` package to have `NODE_ENV` commands work in related package scripts (thank you @Shyrro for this suggestion!)
- Add link to the `components-guide.md` for building new package components (resides in `docs/guides`

**Comment by Shyrro** [comment]
For Windows User i think using the `cross-env` package inside the solution might better than encouraging people to install a package on their machine.

I'll open a PR soon so that it works for Windows users out of the box
