### ISSUE TITLE
Modal not returning focus on close by default

### ISSUE THREAD

**Issue by Shyrro** [chakra-ui/chakra-ui-vue-next#177]
# Bug report

## Describe the bug

When opening a modal, if `finalFocusRef` is not specified, focus will not be returned to the element that trigerred the modal.

## To reproduce

1. Clone https://github.com/Shyrro/chakra-modal-issue-repro
2. Run `pnpm install` and `pnpm dev`
3. Open your browser on dev url and click on "Open Modal" button
4. Once the modal opens, close it
5. Notice that the button does not have focus ( style of focus is border red so it's noticeable )

## Minimal reproduction

Github repro : https://github.com/Shyrro/chakra-modal-issue-repro

## Expected behavior

When the modal closes, it should return the focus to the button

## System information

- Version of @chakra-ui/vue-next: 1.0.0-alpha.15

**Comment by codebender828** [comment]
@Shyrro I'm considering that we use Zag.js to solve this problem.

**Comment by Shyrro** [comment]
@codebender828 Agreed, i'll try to take a look at it when possible
