### ISSUE TITLE
Add `useMediaQuery` composable

### ISSUE THREAD

**Issue by TylerAPfledderer** [chakra-ui/chakra-ui-vue-next#182]
# Feature request

Add the useMediaQuery composable to the Vue package.

This is an [existing function](https://github.com/chakra-ui/chakra-ui/blob/main/packages/components/media-query/src/use-media-query.ts) in the React package to track state of a given CSS media query.

> Note: In the React package, it uses a hook called [useEnvironment](https://github.com/chakra-ui/chakra-ui/blob/b06b3cca679cc7083826b8629add6db6b8218928/packages/components/env/src/env.tsx#L29). Need to consider whether or not to also add this as a composable and use it in order to make useMediaQuery workable in these early stages of the Chakra package
> See Vue's discussion on [Access to Platform Specific APIs](https://vuejs.org/guide/scaling-up/ssr.html#access-to-platform-specific-apis) in regard to SSR with `useEnvironment`

**Comment by codebender828** [comment]
Closing as this is already on develop
