### ISSUE TITLE
Jest expect methods "do not exist on type `Assertion`"

### ISSUE THREAD

**Issue by TylerAPfledderer** [chakra-ui/chakra-ui-vue-next#187]
# Bug report

## Describe the bug

Via vscode intellisense, errors are being registered for various jest `expect` methods stating:
`Property X does not exist on type 'Assertion'`.

Upon inspection of `expect()` via intellisense tooltip, the type signature being recognized is `Chai.ExpectStatic`.

So instead of `toEqual`, typescript is looking for `equal`, because it is looking at the Chai package that exists in the root `node_modules`

## To reproduce

Occurring within VSCode

## Minimal reproduction

N/A

## Expected behavior

Typescript recognizing Jest methods instead of Chai

## Screenshots

![image](https://user-images.githubusercontent.com/65234762/194427928-f05658a8-077f-4ec8-9c0c-f6742aec6e45.png)

## System information

- OS: Windows
- Browser (if applies): N/A
- Version of @chakra-ui/core: 1.0.0-alpha.13
- Version of Node.js: 16.16.0

## Additional context

These errors do not effect the tests that run. However I personally use the `Error Lens` extension, so it highlights the line of code in red.

**Comment by TylerAPfledderer** [comment]
@Shyrro so the disabling of VSCode's built-in Typescript appears to have been the cause. After re-enabling `TypeScript and JavaScript Language Features` extension and restarted the extension host, the typing was corrected!

Would you be able to verify this before I close the issue?

**Comment by Shyrro** [comment]
@TylerAPfledderer Okay, so i checked from my side, no issue at all

I think that maybe you TS Server had an old cache or something and restarting it did the trick. I think you can close it yes !
