### ISSUE TITLE
Add `useEventListeners` composable

### ISSUE THREAD

**Issue by TylerAPfledderer** [chakra-ui/chakra-ui-vue-next#190]
Sets up callbacks for the `addEventListener` and `removeEventListener` with memoization from `useCallback` and `useEffect`.

See React Package [useEventListeners](https://github.com/chakra-ui/chakra-ui/blob/main/packages/components/clickable/src/use-event-listeners.ts)

**Comment by codebender828** [comment]
We already have a `useEventListener` in this directory:
- `packages/vue-composables/src/use-event-listener.ts`

Will close this for now. Happy to reopen in case the need arises for it or if my understanding is discrepant from the initial disposition
