### ISSUE TITLE
CCheckBox icon not rendering correctly

### ISSUE THREAD

**Issue by Shyrro** [chakra-ui/chakra-ui-vue-next#213]
# Bug report

## Describe the bug

The checkbox renders the raw function instead of the "checked" icon. 

![raw function text](https://i.ibb.co/DVby6rb/Capture-d-e-cran-2022-10-27-a-15-00-43.png)

There are also 99+ errors in the console

## To reproduce

1. Go to https://chakra-ui-vue-next-playground-2zajhe2uw-chakra-ui.vercel.app/c-checkbox/examples/simple-checkbox
2. Select the checkbox
3. If you're under Firefox, no icon is shown. If you're under Chromium based browser, you'll see a weird text. In both cases, inspecting the DOM show a rendered string instead of an icon.

## Expected behavior

For the icon to show instead of the function text to print.
## System information

- OS: All. ( Tested on Mac, Windows and Linux )
- Browser (if applies): Chromium based/FF

## Additional context

Since we see the raw function string, it's probably just a double call somewhere to the render function. Instead of returning the render function, we probably return a function that return the render function which causes the string render instead of what is expected.
The errors in the console are probably unrelated, they probably come from null objects trying to access property before the component finished mounting or something like that. (It's a lead to confirm)

**Comment by codebender828** [comment]
Fixed
