### ISSUE TITLE
Dark option of Semantic tokens doesn't work

### ISSUE THREAD

**Issue by carwack** [chakra-ui/chakra-ui-vue-next#249]
# Bug report

## Describe the bug

When using semantic tokens, it is possible to set a _dark condition key. After setting this, it won't apply when toggling into dark mode. https://chakra-ui.com/docs/styled-system/semantic-tokens

Possible because issue is that `html[data-theme="dark"]` isn't added to the HTML tag. 
_The CSS variables are attached to the host element (CSS selector :host, :root) and cannot react to the components <LightMode /> and <DarkMode />, data-theme attributes nor body class .chakra-ui-dark. It listens to e.g. html[data-theme="dark"]._

## To reproduce

1. Add semantic tokens to theme
```
"bg-default": {
      default: #FFFFFF,
      _dark: #000000
    },
```
2. Toggle to dark mode
3. See error

## Minimal reproduction

The needed html tag attribute should be added to make it work.
see: https://github.com/chakra-ui/chakra-ui/blob/main/packages/components/color-mode/src/color-mode.utils.ts

## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies): [e.g. Chrome, Safari]
- Version of @chakra-ui/core: [e.g. 1.0.0-rc.3]
- Version of Node.js: [e.g. 12.11.1]

**Comment by codebender828** [comment]
Fixed in #251
