### ISSUE TITLE
BUG: CPopper component loses reference element during HMR

### ISSUE THREAD

**Issue by codebender828** [chakra-ui/chakra-ui-vue-next#28]
# Bug report
There's a weird bug I've spent a lot of time trying to figure out but haven't had much progress on yet.

When initially loading the page, the  `vue-popper` composable hook works just fine. However during development(HMR with tie), when the template is changed where it's consumed, the `referenceElement` is no longer found by popperjs, even though it can be logged into the DOM.

TODO: Add reproduction

## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies): [e.g. Chrome, Safari]
- Version of @chakra-ui/core: [e.g. 1.0.0-rc.3]
- Version of Node.js: [e.g. 12.11.1]

**Comment by koca** [comment]
I can take a look, do you have the latest changes on `feat/popover` branch?

**Comment by codebender828** [comment]
Thanks, @koca. Yes. You can run `yarn build` to build all packages and then `yarn dev` to start the playground.

See the `base-vue-popper.vue` file for the latest changes

**Comment by codebender828** [comment]
Will not fix. Closing in favour of Zag.js
