### ISSUE TITLE
Impossible to have "checked" and "disabled" on a checkbox

### ISSUE THREAD

**Issue by Shyrro** [chakra-ui/chakra-ui-vue-next#304]
# Bug report

Current checkbox doesn't allow to have a disabled AND checked checkbox. Noticed this while writing the docs.

## Describe the bug

I want to have this : 

```
<c-stack spacing="5" direction="row">
  <c-checkbox is-disabled>Value 1</c-checkbox>
  <c-checkbox is-disabled default-checked>
    Value 2
  </c-checkbox>
</c-stack>
```

working.
## To reproduce

Import the checkbox and paste the code above. Notice that the checkbox isn't checkx and the attributes for checked are not applied.

## Expected behavior

To have a checkbox that can be both checked and disabled.

**Comment by TylerAPfledderer** [comment]
@Shyrro should this issue be considered closed?

**Comment by Shyrro** [comment]
Hey @TylerAPfledderer , yes i think so, i just don't think it's released yet, it's just on the @dev tag
